""" 
Run the pipeline for SARS-CoV-2_aerosol_bottleneck project.
Author: Will Hannon 
"""

#### ----------------------- Imports ----------------------- ####

import pandas as pd 
from os.path import join

#### -------------------- Configuration -------------------- ####

configfile: "config/snakemake.yml"

#### ----------------------- Targets ----------------------- ####
sample_df = pd.read_csv(config['samples'])
samples = sample_df['Run'].unique()

rule all:
    input: 
        expand(join(config['variant_dir'], "{sample}", "{sample}.varscan.tsv"), sample=["HL-2162"]),
        expand(join(config['variant_dir'], "{sample}", "{sample}.ivar.tsv"), sample=["HL-2162"]),
        expand(join(config['variant_dir'], "{sample}", "{sample}.lofreq.tsv"), sample=["HL-2162"])
        

#### ------------------------ Rules ------------------------ ####

rule clean:
    shell:
        """
        rm -rf logs/
        rm -rf tmp/
        rm -f slurm*.out
        """

include: "rules/process-fastq.smk"
include: "rules/align-fastq.smk"
# include: "rules/filter-primers.smk"
include: "rules/call-variants.smk"
