""" 
Run the pipeline for SARS-CoV-2_aerosol_bottleneck project.
Author: Will Hannon 
"""

#### ----------------------- Imports ----------------------- ####

import pandas as pd 
from os.path import join

#### -------------------- Configuration -------------------- ####

configfile: "config/snakemake.yml"

#### ----------------------- Targets ----------------------- ####
sample_df = pd.read_csv(config['samples'])
# samples = sample_df['Run'].unique()
samples = ["HL-2162", "NGS-01", "NGS-02", "NGS-03"]

rule all:
    input: 
        join(config['variant_dir'], "variants.csv"),
        join(config['coverage_dir'], "merged.untrimmed.depth.tsv"),
        join(config['coverage_dir'], "merged.trimmed.depth.tsv")

#### ------------------------ Rules ------------------------ ####

rule clean:
    shell:
        """
        rm -rf logs/
        rm -rf tmp/
        rm -f slurm*.out
        """

include: "rules/process-fastq.smk"
include: "rules/align-fastq.smk"
include: "rules/filter-primers.smk"
include: "rules/calculate-depth.smk"
include: "rules/call-variants.smk"
