#### ============== snakemake configuration file ============== ####

#### ------------------------- Samples ------------------------ ####

samples: config/samples.csv

#### ------------------------- Genomes ------------------------ ####

ref: ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/009/858/895/GCF_009858895.2_ASM985889v3/GCF_009858895.2_ASM985889v3_genomic.fna.gz
gff: ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/009/858/895/GCF_009858895.2_ASM985889v3/GCF_009858895.2_ASM985889v3_genomic.gff.gz
contig: NC_045512.2

#### ------------------------- Params ------------------------ ####

threads:
  max_cpu: 8

#### -------------------------- Dirs ------------------------- ####

fastq_dir: results/fastq
trim_dir: results/trimmed
align_dir: results/aligned

qc_dir: results/qc
reference_dir: results/reference
