#### ============== snakemake configuration file ============== ####

#### ------------------------- Samples ------------------------ ####

samples: config/samples.csv
primers: config/primers.csv
primer_pairs: config/primer_pairs.tsv
excluded: config/excluded_sites.tsv

#### ------------------------- Genomes ------------------------ ####

ref: ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/009/858/895/GCF_009858895.2_ASM985889v3/GCF_009858895.2_ASM985889v3_genomic.fna.gz
gff: ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/009/858/895/GCF_009858895.2_ASM985889v3/GCF_009858895.2_ASM985889v3_genomic.gff.gz
contig: NC_045512.2

#### -------------------------- Util -------------------------- ####

varscan: https://github.com/dkoboldt/varscan/raw/master/VarScan.v2.4.0.jar
snpeff: http://sourceforge.net/projects/snpeff/files/snpEff_latest_core.zip

#### ------------------------- Params ------------------------ ####

threads:
  max_cpu: 8

variant_calling:
  max_depth: 10000
  min_baseQ: 25
  min_mapQ: 0
  min_coverage: 1
  min_frequency: 0.005
  min_obsv: 1
  strand_filter: 1
  min_pval: 0.001

consensus_calling:
  max_depth: 100000
  min_depth: 10
  min_baseQ: 0
  freq_threshold: 0

primer_calling:
  max_depth: 100000
  min_baseQ: 20
  min_mapQ: 0
  min_frequency: 0.03

#### -------------------------- Dirs ------------------------- ####

fastq_dir: results/fastq
trim_dir: results/trimmed
align_dir: results/aligned
variant_dir: results/variants
coverage_dir: results/coverage
consensus_dir: results/consensus

qc_dir: results/qc
reference_dir: results/reference
tool_dir: results/tools
