#### ============== snakemake configuration file ============== ####

#### ------------------------- Samples ------------------------ ####

samples: samples.csv

#### ------------------------- Genomes ------------------------ ####

ref: ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/009/858/895/GCF_009858895.2_ASM985889v3/GCF_009858895.2_ASM985889v3_genomic.fna.gz
gff: ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/009/858/895/GCF_009858895.2_ASM985889v3/GCF_009858895.2_ASM985889v3_genomic.gff.gz
contig: NC_045512.2

#### ------------------------- Params ------------------------ ####

threads:
  max_cpu: 8

#### -------------------------- Dirs ------------------------- ####

reference_dir: results/reference
annotation_dir: results/annotation
